"""generator_probe.py — is the sequence deterministic in a way MI cannot see?

THE HOLE IN THE INFORMATION BOUND
info_bound.py measured I(past ; next) = 0.0023 bits and closed every model that is a
function of the past, by the data processing inequality.

But that argument is STATISTICAL. Algebraic recovery is EXACT. A deterministic PRNG orbit
has essentially zero measurable mutual information under a plug-in estimator and is still
perfectly predictable once the state is known. So "the information bound closes generator
recovery" was too strong a claim.

WHY THE OBVIOUS TEST DOES NOT WORK HERE
The standard attack — inverse-temper 624 consecutive 32-bit words and check the MT19937
recurrence — needs RAW GENERATOR OUTPUT. We observe prices: a rounded cumulative sum of
nonlinearly transformed draws. Each tick delta carries roughly 4-6 bits after quantization,
the transform is unknown, and 624 words would require reconstructing ~20,000 exact bits from
data that does not contain them. MT recovery would fail on this input even if the generator
WERE MT19937, so a null result would prove nothing. Running it would be theatre.

WHAT ACTUALLY WORKS ON QUANTIZED OUTPUT
Three properties survive the transform, because they are about the SEQUENCE rather than the
bits:

  1. CYCLES. Any finite-state generator repeats. If the state is small enough, the price
     path revisits an exact long subsequence. This bounds the state size from below and
     needs no knowledge of the transform.

  2. REPEATED SUBSTRINGS. For an iid uniform digit sequence of length n, the expected count
     of repeated k-grams is about n^2 / (2 * 10^k). At n = 4M that gives ~0.016 expected
     repeats at k=15, so finding even one long repeat is strong evidence of structure. This
     is a different statistic from MI — it is sensitive to rare exact coincidences that a
     smooth estimator averages away.

  3. LEMPEL-ZIV COMPLEXITY. The LZ76 parse count of a random sequence grows as
     n / log_10(n). A deterministic orbit compresses. LZ is the practical stand-in for
     Kolmogorov complexity and catches structure of any order, not just order k.

All three are cheap, valid on quantized data, and are NOT implied by the MI result.

WHAT A POSITIVE RESULT WOULD MEAN
A long exact repeat, or an LZ ratio well below 1, would mean the sequence is generated by
something with a small reachable state. That would be worth far more than every edge in this
repo combined, so the bar for believing it must be high: verify on a second, non-overlapping
block before drawing any conclusion.

Read-only. No trades.

Run: python3 generator_probe.py --symbol JD100 --ticks 4000000
"""
import argparse, math
import numpy as np
from deriv_api import DerivWS
from derivfetch import fetch_ticks, native_interval


def longest_repeat_len(s, kmax=40):
    """
    Longest k for which some k-gram appears at least twice. Binary search over k with a
    hash set at each step — O(n) per probe, cheap enough at n = 4M.
    """
    n = len(s)

    def has_repeat(k):
        if k <= 0 or k > n:
            return False
        seen = set()
        # rolling hash, base 10 since symbols are digits
        base, mod = 10, (1 << 61) - 1
        h = 0
        p = pow(base, k - 1, mod)
        for i in range(k):
            h = (h * base + int(s[i])) % mod
        seen.add(h)
        for i in range(k, n):
            h = ((h - int(s[i - k]) * p) * base + int(s[i])) % mod
            if h in seen:
                return True
            seen.add(h)
        return False

    lo, hi = 1, kmax
    if not has_repeat(1):
        return 0
    while lo < hi:
        mid = (lo + hi + 1) // 2
        if has_repeat(mid):
            lo = mid
        else:
            hi = mid - 1
    return lo


def lz76_complexity(s, cap=1000000):
    """Lempel-Ziv 1976 parse count on a prefix (full 4M is slow in pure Python)."""
    s = s[:cap]
    n = len(s)
    i, c, l = 0, 1, 1
    k = 1
    kmax = 1
    while l + k <= n:
        if s[i + k - 1] == s[l + k - 1]:
            k += 1
        else:
            kmax = max(kmax, k)
            i += 1
            if i == l:
                c += 1
                l += kmax
                i = 0
                kmax = 1
            k = 1
    if l <= n:
        c += 1
    return c, n


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--symbol", default="JD100")
    ap.add_argument("--ticks", type=int, default=4000000)
    ap.add_argument("--lz-cap", type=int, default=300000)
    ap.add_argument("--out", default="../results/generator_probe.md")
    a = ap.parse_args()

    ws = DerivWS(token="")
    print(f"fetching {a.ticks} unique ticks of {a.symbol}...")
    t, p, pip = fetch_ticks(ws, a.symbol, a.ticks)
    ws.close()
    v = np.round(p * (10 ** pip)).astype(np.int64)
    dig = (v % 10).astype(np.int8)
    n = len(dig)
    days = (t[-1] - t[0]) / 86400
    print(f"  {n} ticks, {days:.1f} days\n")

    rng = np.random.default_rng(0)
    ref = rng.integers(0, 10, n).astype(np.int8)

    # ---- 1. cycle detection ---------------------------------------------
    print("=" * 72)
    print("1. EXACT CYCLE — does the price path revisit a long subsequence?")
    print("=" * 72)
    L = longest_repeat_len(dig, kmax=40)
    Lr = longest_repeat_len(ref, kmax=40)
    exp_k = 2 * math.log10(n) if n > 1 else 0
    print(f"  longest repeated digit run, REAL      : {L}")
    print(f"  longest repeated digit run, uniform   : {Lr}")
    print(f"  theoretical expectation ~2*log10(n)   : {exp_k:.1f}")
    print(f"  expected repeats at k=15 for n={n}: "
          f"{n*n/(2*10**15):.4f}")
    cyc = L > exp_k + 6
    print(f"  -> {'STRUCTURE: repeat far longer than chance' if cyc else 'consistent with an iid draw'}")

    # ---- 2. Lempel-Ziv --------------------------------------------------
    print(f"\n{'='*72}")
    print(f"2. LEMPEL-ZIV COMPLEXITY (first {a.lz_cap} symbols)")
    print("=" * 72)
    c_real, nn = lz76_complexity(dig, a.lz_cap)
    c_ref, _ = lz76_complexity(ref, a.lz_cap)
    norm = nn / math.log(nn, 10)
    print(f"  real     parse count {c_real:>8}   normalised {c_real/norm:.5f}")
    print(f"  uniform  parse count {c_ref:>8}   normalised {c_ref/norm:.5f}")
    print(f"  ratio real/uniform {c_real/c_ref:.5f}")
    lz_flag = (c_real / c_ref) < 0.98
    print(f"  -> {'COMPRESSIBLE: deterministic structure' if lz_flag else 'incompressible, same as an iid draw'}")

    # ---- 3. digit marginal + step alphabet ------------------------------
    print(f"\n{'='*72}")
    print("3. STATE-SIZE HINTS")
    print("=" * 72)
    st = np.diff(v)
    u, c = np.unique(st, return_counts=True)
    print(f"  distinct step values: {len(u)}  (a tiny alphabet would bound the state)")
    print(f"  most common steps: "
          + ", ".join(f"{int(x)}:{y/len(st)*100:.1f}%"
                      for x, y in sorted(zip(u, c), key=lambda z: -z[1])[:6]))
    counts = np.bincount(dig, minlength=10)
    chi = float(((counts - n/10) ** 2 / (n/10)).sum())
    print(f"  digit marginal chi2 = {chi:.1f} on 9 df (critical 21.7 at p=0.01)")

    # ---- verdict ---------------------------------------------------------
    print(f"\n{'='*72}")
    print("VERDICT")
    print("=" * 72)
    if cyc or lz_flag:
        print("  STRUCTURE DETECTED. This would be worth more than every edge in the")
        print("  repo combined, so treat it as a hypothesis, not a finding:")
        print("   1. re-run on a second, non-overlapping 4M block")
        print("   2. re-run on a different symbol — a shared generator would show both")
        print("   3. locate the repeat and check whether the FULL price path repeats,")
        print("      not just the digit projection")
    else:
        print("  No cycle, no compressibility, uniform marginal. The sequence is")
        print("  indistinguishable from an iid draw by every statistic that survives")
        print("  quantization.")
        print()
        print("  This does NOT prove the generator is cryptographic — an exact algebraic")
        print("  attack would need raw generator output, and we only observe rounded")
        print("  cumulative sums. But it closes the tests that are actually valid on")
        print("  the data we can obtain.")

    with open(a.out, "w") as f:
        f.write(f"# Generator probe — {a.symbol}\n\n{n} ticks, {days:.1f} days.\n\n"
                f"longest repeated run: real {L}, uniform {Lr}, expectation {exp_k:.1f}\n"
                f"LZ76: real {c_real}, uniform {c_ref}, ratio {c_real/c_ref:.5f}\n"
                f"distinct step values {len(u)}, digit marginal chi2 {chi:.1f} on 9 df\n")
    print(f"\nwrote {a.out}")


if __name__ == "__main__":
    main()
